@extends('layouts.app')

@section('title', 'MANAGEMENT CUSTOMERS')

@section('styles')
    <style>
        /* Table Wrapper yang lebih fleksibel */
        .table-responsive {
            max-height: 65vh;
            /* Konsisten sama halaman Users */
            overflow-y: auto;
            border: 1px solid #dee2e6;
            border-radius: 0.375rem;
        }

        /* Biar header tabel tetep di atas pas scroll */
        thead.sticky-top th {
            box-shadow: 0 2px 2px -1px rgba(0, 0, 0, 0.4);
            z-index: 10;
        }

        /* Hide search clear button bawaan browser */
        input[type="search"]::-webkit-search-decoration,
        input[type="search"]::-webkit-search-cancel-button,
        input[type="search"]::-webkit-search-results-button,
        input[type="search"]::-webkit-search-results-decoration {
            display: none;
        }
    </style>
@endsection

@section('content')
    <div class="container-fluid mt-4 pb-5">

        <div class="row g-3 mb-3 align-items-center justify-content-between">
            <div class="col-12 col-md-auto">
                <h5 class="fw-bold text-primary mb-0 text-uppercase">
                    <i class="bi bi-building-fill me-2"></i>Management Customers
                </h5>
            </div>

            <div class="col-12 col-md-4">
                <div class="input-group shadow-sm">
                    <span class="input-group-text bg-white border-end-0 text-muted">
                        <i class="bi bi-search"></i>
                    </span>
                    <input type="search" class="form-control border-start-0 ps-0" placeholder="Search customer..."
                        id="search-customer" autocomplete="off">

                    <span class="input-group-text bg-white" id="loading-spinner" style="display: none;">
                        <div class="spinner-border spinner-border-sm text-primary" role="status"></div>
                    </span>
                </div>
            </div>
        </div>

        <div class="card shadow-sm border-0 mb-4">
            <div class="card-body p-0">
                <div class="table-responsive">
                    <table class="table table-hover table-bordered table-striped align-middle text-nowrap mb-0"
                        id="customer-table">
                        <thead class="table-primary sticky-top text-center text-uppercase small">
                            <tr>
                                <th style="width: 50px;">No</th>
                                <th>Customer Code</th>
                                <th>Customer Name</th>
                                <th>Department</th>
                                <th style="width: 100px;">Action</th>
                            </tr>
                        </thead>
                        <tbody id="customer-table-body" class="small">
                            {{-- Data Generated by AJAX --}}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        @php
            $backUrl = match (auth()->user()->department->type()) {
                'management' => route('management'),
                'engineering' => route('engineering'),
                'marketing' => route('marketing'),
                default => route('login'),
            };
        @endphp

        <div class="row justify-content-between align-items-center">
            <div class="col-auto">
                <a href="{{ $backUrl }}" class="btn btn-secondary px-4 border-3 border-light-subtle shadow-sm">
                    <i class="bi bi-arrow-left me-2"></i>Back
                </a>
            </div>
            <div class="col-auto">
                <a href="{{ route('marketing.customers.create') }}"
                    class="btn btn-primary px-4 border-3 border-light-subtle shadow-sm rounded-pill fw-bold">
                    <i class="bi bi-plus-lg me-2"></i>Add Customer
                </a>
            </div>
        </div>

    </div>

    <div class="modal fade" id="deleteCustomerModal" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <form method="POST" id="deleteCustomerForm" class="modal-content border-0 shadow">
                @csrf
                @method('DELETE')
                <div class="modal-header bg-danger text-white">
                    <h5 class="modal-title fw-bold">
                        <i class="bi bi-exclamation-triangle-fill me-2"></i>Delete Customer
                    </h5>
                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"
                        aria-label="Close"></button>
                </div>
                <div class="modal-body text-center py-4">
                    <p class="fs-5 mb-1">Are you sure you want to delete?</p>
                    <h4 class="fw-bold text-danger" id="deleteCustomerName">Customer Name</h4>
                    <p class="text-muted small">This action cannot be undone.</p>
                </div>
                <div class="modal-footer bg-light justify-content-center">
                    <button type="button" class="btn btn-secondary px-4" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-danger px-4">Delete Permanently</button>
                </div>
            </form>
        </div>
    </div>

    <x-toast />
@endsection

@section('scripts')
    <script type="module">
        // --- 1. SETUP & UTILS ---
        const $loading = $('#loading-spinner');
        const $tableBody = $('#customer-table-body');

        // Fetch Data Function
        function fetchCustomers(keyword = '', page = 1) {
            $loading.show();
            $.ajax({
                url: `{{ route('marketing.customers.search') }}`,
                type: 'GET',
                data: {
                    keyword: keyword,
                    page: page
                },
                success: function(response) {
                    $tableBody.html(response.html);

                    // Logic Pagination (kalau ada container pagination di view)
                    // $('#pagination-links').html(response.pagination);

                    // Scroll smooth kalau hasil search update
                    if (keyword) {
                        $('html, body').animate({
                            scrollTop: $('#customer-table').offset().top - 150
                        }, 200);
                    }
                },
                complete: function() {
                    $loading.hide();
                },
                error: function() {
                    // Silent fail or toast
                    console.error('Failed to load customers');
                }
            });
        }

        // --- 2. EVENT LISTENERS ---
        $(document).ready(function() {

            // Search Debounce
            let debounceTimer;
            $('#search-customer').on('keyup', function() {
                clearTimeout(debounceTimer);
                const keyword = $(this).val();
                debounceTimer = setTimeout(() => {
                    fetchCustomers(keyword);
                }, 400);
            });

            // Delegasi Tombol Delete
            $(document).on('click', '.btn-delete-customer', function() {
                const id = $(this).data('id');
                const name = $(this).data('name');
                const url = `{{ url('marketing/customers/delete-customer') }}/${id}`;

                $('#deleteCustomerForm').attr('action', url);
                $('#deleteCustomerName').text(name);

                new bootstrap.Modal(document.getElementById('deleteCustomerModal')).show();
            });

            // Initial Fetch
            fetchCustomers();
        });
    </script>
@endsection
