@extends('layouts.app')

@section('title', 'MANAGEMENT USERS')

@section('styles')
    <style>
        /* Hide password eye di Edge/IE */
        input::-ms-reveal,
        input::-ms-clear {
            display: none;
        }

        /* Table Wrapper yang lebih fleksibel */
        .table-responsive {
            max-height: 60vh;
            /* Di PC bisa liat banyak data */
            overflow-y: auto;
            border: 1px solid #dee2e6;
            border-radius: 0.375rem;
        }

        /* Biar header tabel tetep di atas pas scroll */
        thead.sticky-top th {
            box-shadow: 0 2px 2px -1px rgba(0, 0, 0, 0.4);
            z-index: 10;
        }
    </style>
@endsection

@section('content')
    <div class="container-fluid mt-3">
        <div class="row g-3 mb-3 align-items-center justify-content-between">
            <div class="col-12 col-md-auto">
                <h5 class="fw-bold text-primary mb-0 text-uppercase">
                    <i class="bi bi-people-fill me-2"></i>Management Users
                </h5>
            </div>

            <div class="col-12 col-md-4">
                <div class="input-group shadow-sm">
                    <span class="input-group-text bg-white border-end-0 text-muted">
                        <i class="bi bi-search"></i>
                    </span>
                    <input type="search" class="form-control border-start-0 ps-0" placeholder="Search user by name or ID..."
                        id="search-user" autocomplete="off">

                    <span class="input-group-text bg-white" id="loading-spinner" style="display: none;">
                        <div class="spinner-border spinner-border-sm text-primary" role="status"></div>
                    </span>
                </div>
            </div>
        </div>

        <div class="card shadow-sm border-0 mb-3">
            <div class="card-body p-0">
                <div class="table-responsive">
                    <table class="table table-hover table-bordered table-striped align-middle mb-0 text-nowrap"
                        id="user-table">
                        <thead class="table-primary sticky-top text-center text-uppercase small">
                            <tr>
                                <th style="width: 50px;">No</th>
                                <th>ID User</th>
                                <th>Name</th>
                                <th>Department</th>
                                <th>WhatsApp</th>
                                <th>Email</th>
                                <th style="width: 50px;">Checked</th>
                                <th style="width: 50px;">Approved</th>
                                <th style="width: 120px">Action</th>
                            </tr>
                        </thead>
                        <tbody id="user-table-body" class="small">
                            {{-- Data Generated by AJAX --}}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        @php
            $backUrl = match (auth()->user()->department->type()) {
                'management' => route('management'),
                'engineering' => route('engineering'),
                'marketing' => route('marketing'),
                default => route('login'),
            };
        @endphp

        <div class="row justify-content-between align-items-center sticky-bottom">
            <div class="col-auto">
                <a href="{{ $backUrl }}" class="btn btn-secondary px-4 border-3 border-light-subtle shadow-sm">
                    <i class="bi bi-arrow-left me-2"></i>Back
                </a>
            </div>
            <div class="col-auto">
                <button class="btn btn-primary px-4 border-3 border-light-subtle shadow-sm rounded-pill fw-bold"
                    data-bs-toggle="modal" data-bs-target="#userModal" id="btn-add-user">
                    <i class="bi bi-plus-lg me-2"></i>Add User
                </button>
            </div>
        </div>

    </div>

    <div class="modal fade" id="userModal" tabindex="-1" aria-hidden="true" data-bs-backdrop="static">
        <div class="modal-dialog">
            <form class="modal-content needs-validation" method="POST" id="userForm" novalidate>
                @csrf

                <div class="modal-header bg-primary text-white">
                    <h5 class="modal-title fw-bold" id="userModalLabel">Add User</h5>
                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"
                        aria-label="Close"></button>
                </div>

                <div class="modal-body">
                    <div class="mb-3">
                        <label for="id" class="form-label fw-bold">ID User</label>
                        <input type="text" class="form-control" id="id" name="id" pattern="^\d{5}$"
                            inputmode="numeric" minlength="5" maxlength="5" required
                            placeholder="5 Digit ID (e.g. 12345)">
                        <div class="invalid-feedback">ID User must be exactly 5 digits.</div>
                    </div>

                    <div class="mb-3">
                        <label for="name" class="form-label fw-bold">Full Name</label>
                        <input type="text" class="form-control" id="name" name="name" pattern="^[A-Za-z\s]+$"
                            required placeholder="John Doe">
                        <div class="invalid-feedback">Name must contain letters only.</div>
                    </div>

                    <div class="mb-3">
                        <label for="department" class="form-label fw-bold">Department</label>
                        <select class="form-select" id="department" name="department_id" required>
                            <option value="" disabled selected>Choose Department...</option>
                            @foreach ($departments as $department)
                                <option value="{{ $department->id }}">{{ $department->name }}</option>
                            @endforeach
                        </select>
                        <div class="invalid-feedback">Please select a department.</div>
                    </div>

                    <div class="row g-2 mb-3">
                        <div class="col-6">
                            <label for="whatsapp" class="form-label fw-bold">WhatsApp</label>
                            <input type="tel" id="whatsapp" name="whatsapp" class="form-control" placeholder="0812..."
                                inputmode="numeric" pattern="^(?:\+62|62)?0?[0-9]{9,13}$" required>
                            <div class="invalid-feedback">Invalid number.</div>
                        </div>
                        <div class="col-6">
                            <label for="email" class="form-label fw-bold">Email</label>
                            <input type="email" class="form-control" id="email" name="email" required
                                placeholder="@example.com">
                            <div class="invalid-feedback">Invalid email.</div>
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="password" class="form-label fw-bold">Password</label>
                        <div class="input-group has-validation">
                            <input type="password" class="form-control" id="password" name="password" minlength="8"
                                pattern="^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[\W_]).+$" autocomplete="new-password">

                            <button class="btn btn-outline-secondary" type="button" id="togglePassword">
                                <i class="bi bi-eye"></i>
                            </button>

                            <div class="invalid-feedback">
                                Min 8 chars, Uppercase, Lowercase, Number, Symbol.
                            </div>
                        </div>
                    </div>

                    <div class="d-flex gap-4 p-3 bg-light rounded border">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="checked" name="checked"
                                value="1">
                            <label class="form-check-label fw-bold" for="checked">Can Check</label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="approved" name="approved"
                                value="1">
                            <label class="form-check-label fw-bold" for="approved">Can Approve</label>
                        </div>
                    </div>
                </div>

                <div class="modal-footer bg-light">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary px-4">Save User</button>
                </div>
            </form>
        </div>
    </div>

    <div class="modal fade" id="deleteUserModal" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <form method="POST" id="deleteUserForm" class="modal-content border-0 shadow">
                @csrf
                @method('DELETE')
                <div class="modal-header bg-danger text-white">
                    <h5 class="modal-title fw-bold"><i class="bi bi-exclamation-triangle-fill me-2"></i>Delete User</h5>
                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"
                        aria-label="Close"></button>
                </div>
                <div class="modal-body text-center py-4">
                    <p class="fs-5 mb-1">Are you sure you want to delete?</p>
                    <h4 class="fw-bold text-danger" id="deleteUserName">User Name</h4>
                    <p class="text-muted small">This action cannot be undone.</p>
                </div>
                <div class="modal-footer bg-light justify-content-center">
                    <button type="button" class="btn btn-secondary px-4" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-danger px-4">Delete Permanently</button>
                </div>
            </form>
        </div>
    </div>

    <x-toast />
@endsection

@section('scripts')
    <script type="module">
        // --- 1. SETUP & UTILS ---
        const $loading = $('#loading-spinner');
        const $tableBody = $('#user-table-body');

        // Fetch Data Function
        function fetchUsers(keyword = '') {
            $loading.show();
            $.ajax({
                url: `{{ route('marketing.users.search') }}`,
                type: 'GET',
                data: {
                    keyword: keyword
                },
                success: function(response) {
                    $tableBody.html(response.html);
                    // Scroll smooth ke tabel
                    if (keyword) {
                        $('html, body').animate({
                            scrollTop: $('#user-table').offset().top - 150
                        }, 200);
                    }
                },
                complete: function() {
                    $loading.hide();
                },
                error: function() {
                    alert('Failed to load data.');
                }
            });
        }

        // Logic Dept Check (Marketing/Management Auto Check)
        function checkDepartment(departmentId, approved = false, checked = false) {
            const $checked = $('#checked');
            const $approved = $('#approved');

            // Reset dulu state-nya
            $checked.prop('disabled', false).prop('checked', checked);
            $approved.prop('disabled', false).prop('checked', approved);

            const optionText = $('#department option[value="' + departmentId + '"]').text().trim().toLowerCase();

            if (optionText.includes('marketing')) {
                $checked.prop({
                    checked: true,
                    disabled: true
                });
                $approved.prop({
                    checked: true,
                    disabled: true
                });
            } else if (optionText.includes('management')) {
                $checked.prop({
                    checked: true,
                    disabled: true
                });
                $approved.prop({
                    checked: true,
                    disabled: true
                });
            }
        }

        // --- 2. EVENT LISTENERS ---
        $(document).ready(function() {

            // Handle Old Error (Reopen modal if validation fail)
            @if ($errors->any() && old('id'))
                new bootstrap.Modal(document.getElementById('userModal')).show();
            @endif

            // Search Debounce
            let debounceTimer;
            $('#search-user').on('keyup', function() {
                clearTimeout(debounceTimer);
                const keyword = $(this).val();
                debounceTimer = setTimeout(() => fetchUsers(keyword), 400);
            });

            // Button Add User
            $('#btn-add-user').click(function() {
                $('#userForm').trigger('reset');
                $('#userForm').removeClass('was-validated');
                $('#userModalLabel').text('Add New User');
                $('#userForm').attr('action', "{{ route('marketing.users.store') }}");
                $('#password').prop('required', true); // Password wajib kalau Add
                $('#id').prop('readonly', false);
            });

            // Toggle Password
            $('#togglePassword').on('click', function() {
                const $input = $('#password');
                const $icon = $(this).find('i');
                const type = $input.attr('type') === 'password' ? 'text' : 'password';
                $input.attr('type', type);
                $icon.toggleClass('bi-eye bi-eye-slash');
            });

            // Department Change
            $('#department').change(function() {
                checkDepartment($(this).val());
            });

            // Button Edit (Delegation)
            $(document).on('click', '.btn-edit-user', function() {
                const data = $(this).data();

                $('#id').val(data.id).prop('readonly', true); // ID gaboleh ganti
                $('#name').val(data.name);
                $('#email').val(data.email);
                $('#department').val(data.department);

                // Parse WA
                let wa = String(data.whatsapp || '').replace(/\D/g, '').replace(/^62/, '');
                $('#whatsapp').val(wa);

                // Password opsional kalau edit
                $('#password').val('').prop('required', false);

                checkDepartment(data.department, data.approved, data.checked);

                $('#userModalLabel').text('Edit User');
                $('#userForm').attr('action', `{{ url('marketing/users/update-user') }}/${data.id}`);

                new bootstrap.Modal(document.getElementById('userModal')).show();
            });

            // Button Delete (Delegation)
            $(document).on('click', '.btn-delete-user', function() {
                const id = $(this).data('id');
                const name = $(this).data('name');
                $('#deleteUserForm').attr('action', `{{ url('marketing/users/delete-user') }}/${id}`);
                $('#deleteUserName').text(name);
                new bootstrap.Modal(document.getElementById('deleteUserModal')).show();
            });

            // Validation Submit
            $('.needs-validation').on('submit', function(e) {
                if (!this.checkValidity()) {
                    e.preventDefault();
                    e.stopPropagation();
                } else {
                    // Enable field disabled biar ke-submit valuenya
                    $('#checked, #approved').prop('disabled', false);
                }
                $(this).addClass('was-validated');
            });

            // Load Initial Data
            fetchUsers();
        });
    </script>
@endsection
